name: kisuj_ci_cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
      - name: checkout source code.
        uses: actions/checkout@v3

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: check npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env

      - name: build server files
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: zip file
        run: zip -r kisuj.zip ./dist ./before_deploy.sh ./after_deploy.sh ./appspec.yml ./.env ./package.json

      - name: aws configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to s3
        run: aws s3 cp --region ap-northeast-2 ./kisuj.zip s3://kisuj-build/deploy/

      - name: deploy with aws codedeploy
        run: aws deploy create-deployment
          --application-name kisuj-codedeploy
          --file-exists-behavior OVERWRITE
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name kisuj-group
          --s3-location bucket=kisuj-build,bundleType=zip,key=deploy/kisuj.zip
